services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - NEXTAUTH_SECRET=7GLrKVb1X6lzKgnfdogjrJqZrA8UD98Be1KNJcehgjk=
      - NEXTAUTH_URL=http://localhost:3000