services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # - DATABASE_URL=postgresql://postgres.zofzcekhhzrlujxmprcw:Ka5+bwIXdbSwUMovu7KHO9MVlyB5Wn2xgsW95WiUGqg=@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres