services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development