import type { Metadata } from "next";
import "./globals.css";
import AuthContext from './context/AuthContext';
// import getCurrentUser from './actions/getCurrentUser';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode}>) {
  // const currentUser = await getCurrentUser()
  return (
    <html lang="ja">
      <body>
        <AuthContext>
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
